name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
      - master
      - dev
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
      - master
      - dev

permissions:
  contents: read
  pull-requests: write

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
        env:
          NODE_ENV: production
          VITE_AZURE_FUNCTION_URL: ${{ secrets.VITE_AZURE_FUNCTION_URL }}
          VITE_AZURE_FUNCTION_KEY: ${{ secrets.VITE_AZURE_FUNCTION_KEY }}

      - name: Copy staticwebapp config to dist
        run: cp staticwebapp.config.json dist/

      - name: Debug - Check build output
        run: |
          echo "Build completed. Checking dist directory:"
          ls -la dist/
          echo "Current working directory:"
          pwd

      - name: Debug - Check secrets availability
        run: |
          echo "Checking if Azure token secret exists..."
          if [ -z "${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_HILL_07F6F5700 }}" ]; then
            echo "❌ AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_HILL_07F6F5700 is empty or not set"
            echo "Available secrets (names only):"
            echo "- GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN != '' }}"
          else
            echo "✅ AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_HILL_07F6F5700 is available"
            echo "Token length: ${#AZURE_TOKEN}"
          fi
        env:
          AZURE_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_HILL_07F6F5700 }}

      - name: Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_HILL_07F6F5700 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "dist"
          api_location: "api"
          output_location: ""
          skip_app_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_HILL_07F6F5700 }}
          action: "close"
